
title: Prime Imports SpA
description: Componentes electrónicos originales y kits técnicos para Chile.
url: https://primeimportspa.github.io

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

aux_links:
  "Inicio": /

search_enabled: true

footer_content: "© 2025 Prime Imports SpA – RUT 78.277.312-7"
