title: Prime Imports SpA
description: Componentes electrónicos originales y kits técnicos para makers, técnicos y empresas en Chile.
url: https://primeimportspa.github.io

# Configuración de Jekyll
remote_theme: just-the-docs/just-the-docs

# Plugins necesarios
plugins:
  - jekyll-remote-theme

# Opciones del tema just-the-docs
color_scheme: dark  # Puedes cambiarlo a "light" si prefieres

# Navegación principal
nav_external_links:
  - title: Inicio
    url: /
  - title: Kits
    children:
      - title: Kit Prime IoT Básico
        url: /kits/iot-basico/
      - title: Kit Prime Conectores Pro
        url: /kits/conectores-pro/
      - title: Kit Prime Protección
        url: /kits/proteccion/
      - title: Kit Prime Huerto Inteligente
        url: /kits/huerto-inteligente/
      - title: Kit Prime Técnico – Reparación
        url: /kits/tecnico-reparacion/
      - title: Ventiladores 24V para Industria
        url: /kits/industrial-24v/
  - title: Blog Técnico
    url: /blog/
  - title: Contacto
    url: /contacto/

# Habilitar búsqueda
search_enabled: true

# Pie de página
footer_content: "© 2025 Prime Imports SpA – RUT 78.277.312-7"
